### ISSUE TITLE
Failed: H2ScalaEventAdapterTest

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-jdbc#334]
```
[info] H2ScalaEventAdapterTest:
2020-02-03 15:40:48,189 - akka.event.slf4j.Slf4jLogger -> INFO [test-akka.actor.default-dispatcher-4] Slf4jLogger - Slf4jLogger started
[info] - should apply event adapter when querying events for actor with pid 'my-1' *** FAILED *** (10 seconds, 170 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsg while waiting for OnNext(EventEnvelope(Sequence(1),my-1,1,EventRestored(1)))
[info]   at scala.Predef$.assert(Predef.scala:223)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:418)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:404)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:404)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:923)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:369)
[info]   at akka.persistence.jdbc.query.EventAdapterTest.$anonfun$new$4(EventAdapterTest.scala:63)
[info]   at akka.persistence.jdbc.query.EventAdapterTest.$anonfun$new$4$adapted(EventAdapterTest.scala:58)
[info]   at akka.persistence.jdbc.query.ScalaJdbcReadJournalOperations.$anonfun$withEventsByPersistenceId$1(QueryTestSpec.scala:82)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]   at akka.testkit.TestKitBase.within(TestKit.scala:375)
[info]   at akka.testkit.TestKitBase.within$(TestKit.scala:363)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-jdbc/actions/runs/3748097009/jobs/6365048028#step:6:354
