### ISSUE TITLE
The incompatible Akka versions exception occured.

### ISSUE THREAD

**Issue by taeguk** [akka/akka-persistence-jdbc#381]
## Environment
* Akka : 2.6.1 (akka-actor-typed, akka-persistence-typed, akka-persistence-query, etc..)
* Akka HTTP : 10.1.11
* akka-persistence-jdbc : 3.5.3

## Occured exception
```
Detected java.lang.NoSuchMethodError error, which MAY be caused by incompatible Akka versions on the classpath. Please note that a given Akka version MUST be the same across all modules of Akka that you are using, e.g. if you use akka-actor [2.6.1 (resolved from current classpath)] all other core Akka modules MUST be of the same version. External projects like Alpakka, Persistence plugins or Akka HTTP etc. have their own version numbers - please make sure you're using a compatible set of libraries.                 
Uncaught error from thread [ck-server-akka.persistence.dispatchers.default-plugin-dispatcher-31]: akka.persistence.PersistentRepr.withTimestamp(J)Lakka/persistence/PersistentRepr;, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[ck-server]
java.lang.NoSuchMethodError: akka.persistence.PersistentRepr.withTimestamp(J)Lakka/persistence/PersistentRepr;
	at akka.persistence.jdbc.journal.JdbcAsyncWriteJournal.$anonfun$asyncWriteMessages$2(JdbcAsyncWriteJournal.scala:99)
	at scala.collection.immutable.List.map(List.scala:219)
	at scala.collection.immutable.List.map(List.scala:79)
	at akka.persistence.jdbc.journal.JdbcAsyncWriteJournal.$anonfun$asyncWriteMessages$1(JdbcAsyncWriteJournal.scala:99)
	at scala.collection.immutable.List.map(List.scala:219)
	at scala.collection.immutable.List.map(List.scala:79)
	at akka.persistence.jdbc.journal.JdbcAsyncWriteJournal.asyncWriteMessages(JdbcAsyncWriteJournal.scala:95)
	at akka.persistence.journal.AsyncWriteJournal$$anonfun$receiveWriteJournal$1.$anonfun$applyOrElse$4(AsyncWriteJournal.scala:74)
	at akka.pattern.CircuitBreaker$State.materialize$1(CircuitBreaker.scala:735)
	at akka.pattern.CircuitBreaker$State.callThrough(CircuitBreaker.scala:773)
	at akka.pattern.CircuitBreaker$State.callThrough$(CircuitBreaker.scala:732)
	at akka.pattern.CircuitBreaker$Closed$.callThrough(CircuitBreaker.scala:845)
	at akka.pattern.CircuitBreaker$Closed$.invoke(CircuitBreaker.scala:854)
	at akka.pattern.CircuitBreaker.withCircuitBreaker(CircuitBreaker.scala:266)
	at akka.persistence.journal.AsyncWriteJournal$$anonfun$receiveWriteJournal$1.applyOrElse(AsyncWriteJournal.scala:74)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:241)
	at akka.actor.Actor.aroundReceive(Actor.scala:533)
	at akka.actor.Actor.aroundReceive$(Actor.scala:531)
	at akka.persistence.jdbc.journal.JdbcAsyncWriteJournal.aroundReceive(JdbcAsyncWriteJournal.scala:53)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
	at akka.actor.ActorCell.invoke(ActorCell.scala:543)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at kamon.instrumentation.executor.ExecutorInstrumentation$InstrumentedThreadPool$TimingRunnable.run(ExecutorInstrumentation.scala:428)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## Workaround
- **It works if using `3.5.2` for `akka-persistence-jdbc` instead of the lastest (`3.5.3`)**

**Comment by patriknw** [comment]
Have you tried with Akka 2.6.4?

**Comment by taeguk** [comment]
No, I haven't. I can't upgrade akka version to the lastest now. I will do it when possible.

**Comment by taeguk** [comment]
It works with akka 2.6.4
