### ISSUE TITLE
Failed: H2ScalaEventsByTagTest

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-jdbc#482]
```
[info] - should find all events by tag even when lots of events are persisted concurrently *** FAILED *** (1 minute)
[info]   java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 58466419348 nanoseconds
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:368)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:359)
[info]   at akka.persistence.jdbc.query.EventsByTagTest.$anonfun$new$35(EventsByTagTest.scala:214)
[info]   at akka.persistence.jdbc.query.EventsByTagTest.$anonfun$new$35$adapted(EventsByTagTest.scala:213)
[info]   at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:162)
[info]   at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:
```

Underlying cause appears to be:

```
Exception in thread "slick.db-5" java.lang.IllegalArgumentException: requirement failed: count cannot be increased
	at scala.Predef$.require(Predef.scala:281)
	at slick.util.ManagedArrayBlockingQueue.$anonfun$increaseInUseCount$1(ManagedArrayBlockingQueue.scala:43)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at slick.util.ManagedArrayBlockingQueue.locked(ManagedArrayBlockingQueue.scala:201)
	at slick.util.ManagedArrayBlockingQueue.increaseInUseCount(ManagedArrayBlockingQueue.scala:42)
	at slick.util.AsyncExecutor$$anon$1$$anon$2.beforeExecute(AsyncExecutor.scala:117)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by chbatey** [comment]
https://travis-ci.com/github/akka/akka-persistence-jdbc/jobs/470344115

**Comment by ignasi35** [comment]
Again, except this time the failure was on the H2 flavor of the test: (it was MySQL's on the case @chbatey reported above)

https://travis-ci.com/github/akka/akka-persistence-jdbc/jobs/474105442#L960
