### ISSUE TITLE
Failed: find all events by tag even when lots of events are persisted concurrently

### ISSUE THREAD

**Issue by octonato** [akka/akka-persistence-jdbc#520]
This is not from a nightly build, but normal PR build. 

I have seen this failing twice (for h2 and for mysql). 

```scala
[info] - should find all events by tag even when lots of events are persisted concurrently *** FAILED *** (1 minute)
[info]   java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 58777273596 nanoseconds
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:368)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:359)
[info]   at akka.persistence.jdbc.query.EventsByTagTest.$anonfun$new$35(EventsByTagTest.scala:214)
[info]   at akka.persistence.jdbc.query.EventsByTagTest.$anonfun$new$35$adapted(EventsByTagTest.scala:213)
[info]   at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:646)
[info]   at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:642)
[info]   at scala.collection.AbstractIterable.foldLeft(Iterable.scala:919)
[info]   at akka.persistence.jdbc.query.EventsByTagTest.$anonfun$new$34(EventsByTagTest.scala:213)
[info]   at akka.persistence.jdbc.query.EventsByTagTest.$anonfun$new$34$adapted(EventsByTagTest.scala:211)
[info]   at akka.persistence.jdbc.query.ScalaJdbcReadJournalOperations.$anonfun$withEventsByTag$1(QueryTestSpec.scala:96)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]   at akka.testkit.TestKitBase.within(TestKit.scala:416)

```

**Comment by octonato** [comment]
Oh, this was already reported in #482
