### ISSUE TITLE
Failed: H2ScalaEventsByTagTest

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-jdbc#540]
https://github.com/akka/akka-persistence-jdbc/runs/2656339029?check_suite_focus=true

```
[info] - should find all events by tag even when lots of events are persisted concurrently *** FAILED *** (1 minute)
662
[info]   java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 58297543317 nanoseconds
663
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:368)
664
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:359)
665
[info]   at akka.persistence.jdbc.query.EventsByTagTest.$anonfun$new$35(EventsByTagTest.scala:214)
666
[info]   at akka.persistence.jdbc.query.EventsByTagTest.$anonfun$new$35$adapted(EventsByTagTest.scala:213)
667
[info]   at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
668
[info]   at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
669
[info]   at scala.collection.immutable.Range.foreach(Range.scala:158)
670
[info]   at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
671
[info]   at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
672
[info]   at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:108)
673
[info]   at akka.persistence.jdbc.query.EventsByTagTest.$anonfun$new$34(EventsByTagTest.scala:213)
674
[info]   at akka.persistence.jdbc.query.EventsByTagTest.$anonfun$new$34$adapted(EventsByTagTest.scala:211)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-jdbc/runs/3410478161?check_suite_focus=true#step:6:783

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-jdbc/pull/600/checks?check_run_id=3645817404

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-jdbc/pull/600/checks?check_run_id=3645817436

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-jdbc/pull/595/checks?check_run_id=3645812333

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-jdbc/pull/597/checks?check_run_id=3645814541

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-jdbc/pull/596/checks?check_run_id=3645814008

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-jdbc/pull/598/checks?check_run_id=3645815031
